version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: chat-ingest-server-mysql
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maindb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3316:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data: