server:
  port: 8081
spring:
  application:
    name:java-transaction
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3316/maindb?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: user
    password: password
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true